### ISSUE TITLE
[소개] 강진혁입니다

### ISSUE THREAD

**Issue by harry-jk** [DeepLearningProjects/JejuStudy#10]
제주대학교 컴퓨터공학과 4학년 재학중입니다. 
머신러닝에 대해서는 전혀 지식이 없지만 이번기회에 배울수 있을거 같아 신청합니다 :)

jinhyeok.kang@gmail.com

**Comment by hunkim** [comment]
반갑습니다. 제가 제대를 방문중인데 언제 한번 봐요. 방학은 언제부터 언제까지 인가요?

혹시 학생들 중에 관심있는 학생들 더 있으면 소개해주세요. 감사합니다.

**Comment by harry-jk** [comment]
제가 4학년이다 보니 학교에는 잘 없네요 ㅠㅠ
방학은 오늘부터입니다 :)

**Comment by hunkim** [comment]
그렇군요. 혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
