### ISSUE TITLE
[소개]김동하입니다.

### ISSUE THREAD

**Issue by caffeine-driven** [DeepLearningProjects/JejuStudy#11]
카일루아에서 개발자로 근무중인 김동하입니다.

머신러닝에 대해서는 까막눈이지만 같이 배워보고 싶어서 신청했습니다.

이메일 주소는 ghost9087@gmail.com 입니다.

**Comment by hunkim** [comment]
반가워요. 혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
