### ISSUE TITLE
[소개] 민창현입니다. 

### ISSUE THREAD

**Issue by minchang** [DeepLearningProjects/JejuStudy#13]
안녕하세요?
카카오 검색팀에서 검색어 관련 서비스 개발 하고 있는 민창현입니다. 
주로 서비스 개발을 하다 최근에 데이터 분석 업무로 옮겨가고 있어 공부가 필요하여 신청하였습니다. 

메일 주소는 changhyun.min at gmail.com 입니다.

**Comment by hunkim** [comment]
반가워요. 혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
