### ISSUE TITLE
[소개] 임주영입니다.

### ISSUE THREAD

**Issue by JuYoungLim** [DeepLearningProjects/JejuStudy#14]
네오플에서 라이브서비스 분석팀에서  일하고 있고요~
최근 김성훈 교수님 강의를 보고 tensorflow를 배우고 있습니다.

제 이메일은 ju02g(at)naver.com 입니다.

**Comment by hunkim** [comment]
혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
