### ISSUE TITLE
[소개] 송혜원입니다

### ISSUE THREAD

**Issue by SongHye** [DeepLearningProjects/JejuStudy#15]
제주대학교 컴퓨터공학과 3학년 재학중인 송헤원입니다.

아직 딥러닝에 대해 자세하게는 알지 못하지만
저의 최종목표에 한걸음 나아갈 수 있는 기회이기에 신청했습니다.

freyja838@gmail.com

**Comment by hunkim** [comment]
반가워요. 제대 컴공 다른 친구들도 관심있으면 추천 부탁드립니다.

**Comment by hunkim** [comment]
혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
