### ISSUE TITLE
[소개] 백수희입니다

### ISSUE THREAD

**Issue by SooHeeB** [DeepLearningProjects/JejuStudy#17]
카카오에서 검색어관련 분석을 하고 있어요.
요새 tensorFlow에 대한 이야기를 여기저기서 듣고 있는데, 깊게 이해하고 싶어서 신청하게 되었습니다

이메일 주소는 soohee.bsh@gmail.com입니다

**Comment by hunkim** [comment]
반갑습니다.

**Comment by hunkim** [comment]
혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
