### ISSUE TITLE
[소개] 김보경입니다.

### ISSUE THREAD

**Issue by Wef2** [DeepLearningProjects/JejuStudy#18]
제주대학교 4학년 김보경이라고 합니다.

머신러닝을 배울 수 있는 좋은 기회라고 생각하여 신청하게 되었습니다.

qhrud5725@hanmail.net

**Comment by hunkim** [comment]
반가워요.

**Comment by hunkim** [comment]
혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
