### ISSUE TITLE
[소개] 이범재입니다.

### ISSUE THREAD

**Issue by beomjae** [DeepLearningProjects/JejuStudy#2]
제주넷에서 안드로이드 개발자로 일하고 있습니다. 
사람과 커뮤니티 그리고 공간에 대하여 관심이 많습니다.
이메일은 beomjae(at)gmail.com 입니다.

**Comment by hunkim** [comment]
반가워요. 혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
