### ISSUE TITLE
[소개] 정해완입니다.

### ISSUE THREAD

**Issue by haewanj** [DeepLearningProjects/JejuStudy#3]
카카오 소속 다음뉴스 개발자로 최근 하둡기반 업무를 진행하게 되면서 함께 데이터 분석을 알아가는 과정에 있습니다. ML도 향후 도전과제 중 하나였는데, 이렇게 빨리 기회가 찾아와서 신기할 따름입니다. 이번 스터디가 무척 소중한 시간이 되리라 기대합니다.

이메일은 haewanj(at)gmail.com 입니다.

**Comment by hunkim** [comment]
반갑습니다.

**Comment by hunkim** [comment]
혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
