### ISSUE TITLE
[소개] 전무익입니다.

### ISSUE THREAD

**Issue by muik** [DeepLearningProjects/JejuStudy#6]
스타트업과 카카오에서 안드로이드/서버 개발을 했었고, 현재는 소속없이 개인 프로젝트 진행 중인 소프트웨어 엔지니어 입니다.
최근에 tensorflow 튜토리얼을 활용해 [영한 표기 변환기](https://transliterator.herokuapp.com/)를 만들어 보았는데요. 머신러닝을 서비스에 접목하며 활용해보는 것에 흥미를 가지고 있습니다.

이메일은 muikor (at) gmail.com 입니다.

**Comment by hunkim** [comment]
반가워요!!

**Comment by hunkim** [comment]
혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
