### ISSUE TITLE
[소개] 김무훈입니다.

### ISSUE THREAD

**Issue by mu-hun** [DeepLearningProjects/JejuStudy#7]
웹 서비스 개발과 Python을 주로 하며, 오픈소스와 정보 교육에 많은 관심을 가진 서귀포고등학교에 재학중인 학생입니다.

현재 [Lev6](https://github.com/Team-Railgun/Lev6-Layout)라는 웹기반 학교 시간표 관리 서비스를 개발중입니다.

Email : yale2a11@gmail.com

**Comment by hunkim** [comment]
대단하십니다. 반가워요. 모임이 아무래도 제주시근방이 될듯 한데 서귀포쪽이면 참여가능할까요?

**Comment by mu-hun** [comment]
@hunkim 네 학교 수업하고 겹치지만 않으면 버스타고 가면 됩니다 :D

**Comment by mu-hun** [comment]
@hunkim 어.. 잠시만요.
http://doodle.com/poll/xps6whftf4xiwqy5
이번주 금요일 오후 7시 모임인가요? 이러면 학교 수업하고 겹칩니다 :(

**Comment by hunkim** [comment]
요일은 금요일 확정이 아닙니다. 아마 화요일 정도 되지 않을까 싶습니다.

**Comment by hunkim** [comment]
혹시 그룹 메일 받으셨으면 의견을 알려 주세요.

**Comment by mu-hun** [comment]
@hunkim 주중에는 오후 9시까지 학교 야간자율학습 시간이라서 개인적으로 주말에 일정을 잡는걸 선호합니다.

7월 중순부터 방학인데 그 때는 괜찮을지 모르겠네요 :(

**Comment by hunkim** [comment]
http://doodle.com/poll/xps6whftf4xiwqy5 을 보니 많은 분들이 주중 7시를 선호해주셔서 그렇게 가보려고 합니다. 선호하시는 방향으로 시간이 정해지지 못해 죄송합니다.
