### ISSUE TITLE
[소개] 고승원 입니다

### ISSUE THREAD

**Issue by seungwongo** [DeepLearningProjects/JejuStudy#8]
안녕하세요. 저는 현재 ReturnValues 라는 1인 기업을 운영하고 있습니다. SAP ERP 분야 컨설팅 및 웹관련 소프트웨어를 개발하여 판매도 하고 있습니다. 사실 저는 머신러닝에 대해서는 전혀 지식이 없습니다. 하지만 같이 스터디를 한다면 충분히 좋은 성과를 낼 수 있을거라 자신합니다. 좋은 모임이 되었으면 합니다

**Comment by hunkim** [comment]
감사합니다. 혹시 이메일 알려 주시면 메일링 리스트로 연락드리겠습니다.

**Comment by seungwongo** [comment]
seungwon.go@gmail.com

**Comment by hunkim** [comment]
반가워요. 혹시 그룹 메일 받으셨으면 의견을 알려 주세요.
